
export const dummySkills: SkillRecord[] = [
  {
    id: '1',
    title: 'Write Code',
    slug: 'write-code',
    description: 'Learn how to write clean, efficient, and maintainable code following best practices and design patterns.',
    category: 'Development',
    tags: ['coding', 'best-practices', 'programming'],
    installCommand: 'npm install write-code-skill',
    createdAt: '2025-01-15T10:30:00Z',
    authorClerkId: 'user_123456',
    authorEmail: 'john.dev@example.com',
  },
  {
    id: '2',
    title: 'Debug JavaScript',
    slug: 'debug-javascript',
    description: 'Master debugging techniques for JavaScript including browser DevTools, logging strategies, and error handling.',
    category: 'Development',
    tags: ['debugging', 'javascript', 'troubleshooting'],
    installCommand: 'npm install debug-js-skill',
    createdAt: '2025-02-20T14:45:00Z',
    authorClerkId: 'user_789012',
    authorEmail: 'jane.developer@example.com',
  },
  {
    id: '3',
    title: 'React Component Design',
    slug: 'react-component-design',
    description: 'Build scalable React components with proper state management, hooks, and component composition patterns.',
    category: 'Frontend',
    tags: ['react', 'components', 'frontend'],
    installCommand: 'npm install react-component-design',
    createdAt: '2025-01-10T09:15:00Z',
    authorClerkId: 'user_345678',
    authorEmail: 'react.master@example.com',
  },
  {
    id: '4',
    title: 'API Design & REST',
    slug: 'api-design-rest',
    description: 'Design robust REST APIs with proper endpoint structure, error handling, authentication, and documentation.',
    category: 'Backend',
    tags: ['api', 'rest', 'backend', 'design'],
    installCommand: 'npm install api-design-rest',
    createdAt: '2025-03-05T11:20:00Z',
    authorClerkId: 'user_567890',
    authorEmail: 'backend.guru@example.com',
  },
  {
    id: '5',
    title: 'Testing Best Practices',
    slug: 'testing-best-practices',
    description: 'Write comprehensive tests using Jest, React Testing Library, and E2E testing frameworks for reliable applications.',
    category: 'QA',
    tags: ['testing', 'jest', 'quality-assurance'],
    installCommand: 'npm install testing-best-practices',
    createdAt: '2025-02-28T16:30:00Z',
    authorClerkId: 'user_234567',
    authorEmail: 'qa.specialist@example.com',
  },
];
